### ISSUE TITLE
Consertar crash de Adicionar horário em turmas

### ISSUE THREAD

**Issue by jvfd3** [jvfd3/timetabling-UENF#195]
```
ERROR
Cannot read properties of undefined (reading 'current')
TypeError: Cannot read properties of undefined (reading 'current')
    at createHorario (http://127.0.0.1:3000/timetabling-UENF/static/js/bundle.js:8956:3)
    at addHour (http://127.0.0.1:3000/timetabling-UENF/static/js/bundle.js:5407:75)
    at HTMLUnknownElement.callCallback (http://127.0.0.1:3000/timetabling-UENF/static/js/bundle.js:41618:18)
    at Object.invokeGuardedCallbackDev (http://127.0.0.1:3000/timetabling-UENF/static/js/bundle.js:41662:20)
    at invokeGuardedCallback (http://127.0.0.1:3000/timetabling-UENF/static/js/bundle.js:41719:35)
    at invokeGuardedCallbackAndCatchFirstError (http://127.0.0.1:3000/timetabling-UENF/static/js/bundle.js:41733:29)
    at executeDispatch (http://127.0.0.1:3000/timetabling-UENF/static/js/bundle.js:45876:7)
    at processDispatchQueueItemsInOrder (http://127.0.0.1:3000/timetabling-UENF/static/js/bundle.js:45902:11)
    at processDispatchQueue (http://127.0.0.1:3000/timetabling-UENF/static/js/bundle.js:45913:9)
    at dispatchEventsForPlugins (http://127.0.0.1:3000/timetabling-UENF/static/js/bundle.js:45922:7)
```

![Image](https://github.com/jvfd3/timetabling-UENF/assets/10092672/d66bc8d6-894d-4bb1-a1dc-f91b94bf6cfb)

**Comment by jvfd3** [comment]
![image](https://github.com/jvfd3/timetabling-UENF/assets/10092672/b4a26b9a-cc39-4867-95d9-7dbd44798f85)
Fixed

**Comment by jvfd3** [comment]
Certamente eu tava tentando acessar alguma variável do useRef
